### PR TITLE
Py3, PEP8 and venv

### PR DESCRIPTION
**Pull request by fabaff**
Sorry...this PR is now bigger than I want it to be.

- Make the Code run with Python 3.
- The location of `bleah` in /bin caused an error when `python3 setup.py develop` is used. Also, is the `venv` stores its executables in `/bin`. `entry_points` new points to the new location of `bleah` which was renamed to `cli.py`
- Update style in README
- Catch some more exceptions
- Fix some low-hanging PEP8 issues

### CODE REVIEW

**Comment by evilsocket** [comment]
most of these commit are not necessary, will merge a new PR with just the python3 support, not merging mostly style/formatting changes.

**Comment by fabaff** [comment]
Why wouldn't you want that the code follow at least a little bit the most common style element from PEP8? Especially as you already do it at some places. Well, it's your call. Even with the changes which are included will there be approx. 200 style violations be left...

Placing `bleah` in `/bin` will not work in all cases as I already mentioned.

Sorry, in the current state I will not start to work on a package of `bleah` to include it into the Fedora Package Collection as Python 3 support is needed. There are no requirements about the "code quality" of upstream projects in Fedora but it's better to make it easy for people to read the code when they are tracking down issues by following the guidelines they know, are wide-spread and around for almost 20 years.

**Comment by fabaff** [comment]
Oh, now I see the [real issue](https://github.com/evilsocket/bleah/pull/7#issuecomment-331926107) for rejection. Too bad, it's a nice tool but all major distributions will deprecate Python 2.x in the near future.

**Comment by evilsocket** [comment]
> Sorry, in the current state I will not start to work on a package of bleah to include it into the Fedora Package Collection

I never asked to.

opinions

**Comment by fabaff** [comment]
I did I say that you asked. No, I didn't.

**Comment by evilsocket** [comment]
Glad to see we're on the same page. Bye o/

**Pull request closed without merging**
